name: Deploy Application

on:
  push:
    branches:
      - main
      - deploy/aws

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven (skip tests)
        run: mvn clean install -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t zippydelivery/zippydelivery-v1:v1.0 .

      - name: Push Docker Image
        run: docker push zippydelivery/zippydelivery-v1:v1.0

  deploy_self_hosted:
    needs: deploy
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start PostgreSQL and Application using Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Remove existing container (if any)
        run: |
          docker ps -a -q --filter "name=zippydelivery-v1" | grep -q . && docker rm -f zippydelivery-v1 || echo "No container to remove"

      - name: Pull Docker Image
        run: docker pull zippydelivery/zippydelivery-v1:v1.0

      - name: Run Docker Container
        run: |
          docker run -d --name zippydelivery-v1 -p 8080:8080 \
            -e USER_DB=${{ secrets.USER_DB }} \
            -e PASS_DB=${{ secrets.PASS_DB }} \
            -e URL_DB=${{ secrets.URL_DB }} \
            zippydelivery/zippydelivery-v1:v1.0