name: Deploy Application

on:
  push:
    branches:
      - main
      - deploy/aws

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Step 3: Build with Maven (Skip tests)
      - name: Build with Maven (skip tests)
        run: mvn clean install -DskipTests

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build Docker image
      - name: Build Docker Image
        run: docker build -t zippydelivery/zippydelivery-v1:v1.0 .

      # Step 6: Push Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push zippydelivery/zippydelivery-v1:v1.0

      # Step 7: Deploy on self-hosted server
      - name: Deploy on Self-hosted Server
        runs-on: self-hosted
        steps:
          # Step 7.1: Remove existing container (if it exists)
          - name: Remove existing container
            run: docker rm -f zippydelivery-v1 || echo "No container to remove"
          
          # Step 7.2: Pull the new image from Docker Hub
          - name: Pull Docker Image
            run: docker pull zippydelivery/zippydelivery-v1:v1.0

          # Step 7.3: Run the new container
          - name: Run Docker Container
            run: |
              docker run -d --name zippydelivery-v1 -p 8080:8080 -e USER_DB=${{ secrets.USER_DB }} -e PASS_DB='${{ secrets.PASS_DB }}' -e URL_DB=${{ secrets.URL_DB }} zippydelivery/zippydelivery-v1:v1.0